### ISSUE TITLE
LiteLLM Proxy 连接 OpenAI API 失败

### ISSUE THREAD

**Issue by kubbot** [telepace/nexus#134]
## 问题描述

LiteLLM Proxy 服务在尝试调用 OpenAI API 时出现连接错误，导致服务不可用。

## 错误日志

```
litellm.exceptions.APIError: APIError: OpenAIException - Connection error.. 
Received Model Group=openai-gpt-4o-mini
LiteLLM Retried: 1 times, LiteLLM Max Retries: 2

httpcore.ConnectError -> httpx.ConnectError -> openai.APIConnectionError
```

主要错误发生在 TLS 握手阶段：
```python
File "/usr/lib/python3.13/site-packages/httpcore/_async/connection.py", line 156, in _connect
    stream = await stream.start_tls(**kwargs)
```

## 问题分析

1. **网络连接问题**：容器无法访问 OpenAI API 端点
2. **TLS/SSL 问题**：证书验证或 TLS 版本不兼容
3. **缺少 metrics 端点**：大量 `GET /metrics 404` 错误
4. **配置问题**：可能缺少必要的环境变量或代理设置

### 1. 网络连通性检查
```bash
# 在容器内测试网络连接
curl -v https://api.openai.com/v1/models
```

### 2. 配置 HTTP 代理（如需要）
```yaml
environment:
  - HTTP_PROXY=http://proxy.example.com:8080
  - HTTPS_PROXY=http://proxy.example.com:8080
  - NO_PROXY=localhost,127.0.0.1
```

### 3. 添加 metrics 端点
在 LiteLLM 配置中启用 Prometheus metrics：
```python
# 或在启动参数中添加
--enable-prometheus-metrics
```

### 4. 增强错误处理和重试机制
```yaml
# litellm_config.yaml
model_list:
  - model_name: gpt-4o-mini
    litellm_params:
      model: openai/gpt-4o-mini
      timeout: 30
      max_retries: 3
      request_timeout: 60
```

### 5. 添加详细日志
```bash
export LITELLM_LOG=DEBUG
```

## 验收标准

- [ ] LiteLLM Proxy 能够成功连接到 OpenAI API
- [ ] 没有 Connection Error 报错
- [ ] /metrics 端点正常返回数据（200 OK）
- [ ] 通过健康检查：`curl http://localhost:4000/health`
- [ ] 能够成功完成一次 API 调用测试

## 参考资料

- [LiteLLM Proxy 文档](https://docs.litellm.ai/docs/proxy/quick_start)
- [OpenAI API 连接问题排查](https://platform.openai.com/docs/guides/error-codes)
