### ISSUE TITLE
设计：内容图片处理策略与存储方案

### ISSUE THREAD

**Issue by kubbot** [telepace/nexus#143]
# 📋 需求概述

设计并实现一个智能的图片处理策略，根据内容来源和用户意图，为不同类型的图片提供差异化的处理方案，在保证用户体验的同时有效控制成本。

## 🎯 设计目标

1. **成本可控**：避免前期巨大的存储和带宽成本，采用渐进式投入策略
2. **用户体验优化**：根据使用场景提供合适的图片处理方案
3. **技术可行性**：采用成熟稳定的技术方案，确保系统可靠性
4. **可扩展性**：为未来功能升级预留技术架构空间

### 场景1：上传PDF/文档
- **用户意图**：保存重要内容，需要长期保存和反复阅读
- **图片特征**：内嵌图片，通常是图表、截图等关键信息
- **处理策略**：完整提取并存储到S3，确保内容完整性

### 场景2：网页剪藏
- **用户意图**：快速保存网页内容，可能是临时参考
- **图片特征**：外部链接，包含装饰图片和内容图片
- **处理策略**：保持原始链接引用，降低存储成本

### 场景3：复制粘贴
- **用户意图**：快速记录片段信息
- **图片特征**：可能包含base64图片或外部链接
- **处理策略**：根据图片大小和类型智能处理

### 1. 核心处理策略

```yaml
PDF/文档上传:
  - 提取所有内嵌图片
  - 上传至S3存储
  - 在Markdown中使用S3链接引用
  - 保证内容永久可访问

网页剪藏:
  - 保持原始图片链接
  - 记录图片元信息（alt text、尺寸等）
  - 提供失效检测机制
  - 可选的完整保存功能

复制粘贴:
  - 检测图片类型（base64/URL）
  - 小图片（<100KB）自动存储
  - 大图片保持链接或提示用户选择
```

### 2. 智能检测机制

- **可访问性检测**：检测图片是否有跨域限制、防盗链等问题
- **重要性评估**：基于图片位置、大小、上下文判断重要性
- **失效监控**：定期检查外链图片可访问性，提供修复建议

### 3. 用户选择权

```markdown
保存网页时的选项：
□ 快速保存（仅保存文本和链接）
□ 完整保存（包含所有图片）- 需要更多存储空间
□ 智能保存（自动判断重要图片）

用户偏好设置：
- 默认保存模式
- 图片大小阈值
- 自动存储规则
```

### 4. 分级处理规则

| 图片类型 | 大小范围 | 处理方式 | 备注 |
|---------|---------|---------|------|
| 图标/Logo | <50KB | 自动存储 | 提升体验，成本可控 |
| 内容图片 | 50KB-1MB | 用户选择 | 平衡成本与体验 |
| 大图片 | >1MB | 保持链接 | 提供手动保存选项 |
| 关键图表 | 任意大小 | 智能检测+提示 | AI判断重要性 |

### 数据模型扩展

```typescript
// 图片元数据
interface ImageMetadata {
  id: string;
  sourceUrl?: string;        // 原始URL
  s3Key?: string;            // S3存储位置
  type: 'embedded' | 'linked' | 'stored';
  size: number;              // 图片大小
  format: string;            // 图片格式
  altText?: string;          // 替代文本
  importance: 'high' | 'medium' | 'low';
  lastChecked?: Date;        // 最后检查时间
  isAccessible: boolean;     // 是否可访问
}

// 文档扩展字段
interface DocumentExtension {
  imageStrategy: 'full' | 'smart' | 'minimal';
  images: ImageMetadata[];
  totalImageSize: number;
}
```

### 处理流程

```mermaid
graph TD
    A[内容输入] --> B{内容类型判断}
    B -->|PDF/文档| C[完整图片提取]
    B -->|网页| D[智能分析]
    B -->|粘贴| E[格式检测]
    
    C --> F[上传S3]
    D --> G{重要性判断}
    E --> G
    
    G -->|高重要性| F
    G -->|中等| H[用户选择]
    G -->|低重要性| I[保持链接]
    
    H -->|选择保存| F
    H -->|跳过| I
    
    F --> J[更新Markdown引用]
    I --> J
    
    J --> K[渲染展示]
```

### Phase 1 - MVP (第1-2周)
- [x] 实现PDF图片提取和S3存储
- [x] 网页内容保持原始链接
- [x] 基础的Markdown渲染支持
- [x] 简单的用户提示机制

### Phase 2 - 优化 (第3-4周)
- [ ] 增加图片可访问性检测
- [ ] 实现智能重要性判断
- [ ] 提供用户选择界面
- [ ] 添加图片失效提示

### Phase 3 - 完善 (第5-6周)
- [ ] 用户偏好设置
- [ ] 批量图片管理工具
- [ ] 图片代理服务（解决跨域）
- [ ] 存储使用统计和限额管理

## 📈 成功指标

1. **用户满意度**：图片显示正常率 > 95%
2. **成本控制**：存储成本增长 < 用户增长的50%
3. **性能指标**：图片处理不影响文档处理速度
4. **功能使用率**：20%用户使用完整保存功能

## 🔄 后续优化方向

1. **AI增强**：使用AI判断图片内容重要性
2. **压缩优化**：智能图片压缩减少存储
3. **CDN加速**：提升图片加载速度
4. **付费功能**：为高级用户提供无限图片存储

## 📝 设计原则

1. **渐进增强**：从基础功能开始，逐步完善
2. **用户可控**：提供选择权，不强制决策
3. **透明沟通**：清晰告知处理方式和原因
4. **优雅降级**：图片失效时提供良好体验

## 🎨 UI/UX 设计要点

- 在保存时清晰展示不同选项的差异
- 使用图标和颜色区分已存储/外链图片
- 提供图片管理的独立页面
- 失效图片显示友好的占位符和修复建议

## ⚙️ 配置示例

```yaml
image_processing:
  default_strategy: "smart"
  
  thresholds:
    auto_store_size: 50KB
    warning_size: 1MB
    
  pdf_processing:
    extract_all: true
    compress: true
    max_dimension: 2048
    
  web_clipping:
    check_accessibility: true
    preserve_links: true
    
  storage:
    provider: "s3"
    bucket: "nexus-images"
    cdn_enabled: true
```

## 🔍 验收标准

1. PDF文档的所有内嵌图片都能正确提取和显示
2. 网页剪藏保持原始链接，加载速度不受影响
3. 用户可以选择不同的保存策略
4. 图片失效时有明确提示和解决方案
5. 存储成本在可控范围内
6. 所有测试用例通过

---

**相关文档**：
- Product Design Doc
- System Design Doc
- UI设计规范

**优先级**：高
**预计工作量**：3个sprint（6周）
**影响范围**：内容处理、存储、前端渲染
