### ISSUE TITLE
内容公开分享功能

### ISSUE THREAD

**Issue by cubxxw** [telepace/nexus#149]
#### 方案：基于分享令牌的安全分享机制

**URL 结构：**
```
https://domain.com/share/[shareToken]
```

**实现要点：**
- 使用 nanoid 或 UUID 生成唯一的 shareToken
- 分享链接与原始内容 ID 解耦，增强安全性
- 支持设置过期时间和访问次数限制

### 2. 数据库设计

```sql
-- 新增分享表
CREATE TABLE content_shares (
  id UUID PRIMARY KEY,
  content_id UUID REFERENCES content_items(id),
  share_token VARCHAR(32) UNIQUE NOT NULL,
  created_at TIMESTAMP DEFAULT NOW(),
  expires_at TIMESTAMP NULL,
  access_count INTEGER DEFAULT 0,
  max_access_count INTEGER NULL,
  password_hash VARCHAR(255) NULL,
  is_active BOOLEAN DEFAULT TRUE
);

-- 或在现有 content_items 表添加字段
ALTER TABLE content_items 
ADD COLUMN share_token VARCHAR(32) UNIQUE,
ADD COLUMN is_shareable BOOLEAN DEFAULT FALSE,
ADD COLUMN share_expires_at TIMESTAMP NULL;
```

### 3. API 设计

```yaml
# 生成分享链接
POST /api/v1/content/{id}/share
Request:
  expires_in: number (秒)
  max_access_count: number
  password: string (可选)
Response:
  share_url: string
  share_token: string
  expires_at: datetime

# 获取分享内容（无需认证）
GET /api/v1/share/{token}
Query:
  password: string (如果设置了密码)
Response:
  content: ContentPublic
  
# 撤销分享
DELETE /api/v1/content/{id}/share
```

#### 技术栈推荐

**核心库：**
- **react-markdown** - 继续使用，稳定可靠
- **unified 生态系统**：
  - remark-gfm (GitHub 风格)
  - remark-toc (目录生成)
  - rehype-autolink-headings (标题锚点)
  - remark-math + rehype-katex (数学公式)
  - rehype-highlight (代码高亮)

**UI 增强：**
- **@radix-ui/react-scroll-area** - 优化滚动体验
- **react-intersection-observer** - 实现阅读进度
- **medium-zoom** - 图片放大查看
- **copy-to-clipboard** - 代码复制功能

#### 优化重点

1. **视觉层次优化**
   - 参考 Notion 的清晰层次
   - 优化标题、段落间距
   - 使用 Inter 字体提升阅读体验

2. **代码块增强**
   - 添加语言标识
   - 一键复制按钮
   - 行号显示选项
   - 主题切换（Light/Dark）

3. **交互功能**
   - 浮动目录导航
   - 阅读进度指示器
   - 平滑滚动到锚点
   - 选中文字分享

4. **响应式设计**
   - 移动端优化
   - 表格横向滚动
   - 图片自适应
