### ISSUE TITLE
🎨 夜间模式UI设计优化：解决对比度不足和视觉层次问题

### ISSUE THREAD

**Issue by kubbot** [telepace/nexus#216]
## 🎯 问题描述

当前夜间模式界面存在严重的视觉设计问题，影响用户体验和产品可用性。

### 📷 问题截图
[当前界面截图显示的问题]
- 侧边栏与主内容区对比度不足
- 文字可读性差
- 右侧空白区域处理不当
- 缺乏清晰的视觉层次

### 1. 对比度不足问题
- **现状**：文字与背景对比度低于 WCAG AA 标准（4.5:1）
- **影响**：用户难以阅读内容，尤其是"暂无描述"等次要信息
- **位置**：全局文字显示、状态标签、时间信息

### 2. 视觉层次混乱
- **现状**：侧边栏、主内容区、卡片背景颜色过于接近
- **影响**：用户无法快速区分不同功能区域
- **位置**：整体布局结构

### 3. 交互状态不明确
- **现状**：按钮、链接等交互元素在深色模式下不够突出
- **影响**：用户不清楚哪些元素可以点击
- **位置**：导航菜单、内容卡片、操作按钮

### 4. 空间利用不当
- **现状**：右侧大片空白区域缺乏设计处理
- **影响**：界面显得不平衡，空间浪费
- **位置**：主内容区右侧区域

### 1. 建立标准化深色模式颜色系统
```css
:root.dark {
  /* 背景层次 */
  --background: 0 0% 3.9%;           /* 主背景 */
  --background-secondary: 0 0% 6%;   /* 侧边栏背景 */
  --background-tertiary: 0 0% 9%;    /* 卡片背景 */
  
  /* 文字层次 */
  --foreground: 0 0% 98%;            /* 主文字 */
  --foreground-secondary: 0 0% 71%;  /* 次级文字 */
  --foreground-muted: 0 0% 54%;      /* 辅助文字 */
  
  /* 交互状态 */
  --primary: 210 40% 67%;            /* 主色调 */
  --border: 0 0% 15%;                /* 边框色 */
}
```

### 2. 优化组件设计
- **侧边栏**：增强当前页面状态指示，添加悬停效果
- **内容卡片**：增加边框、优化悬停状态、改进状态标签设计
- **空状态**：设计引导性的空状态界面

### 3. 响应式优化
- **空白区域**：添加快捷操作面板或最近访问内容
- **移动端适配**：确保深色模式在不同设备上的一致性

## 🎨 设计规范要求

- [ ] 所有文本对比度达到 WCAG AA 标准（≥4.5:1）
- [ ] 交互元素有明确的视觉反馈
- [ ] 遵循既定的语义化颜色系统
- [ ] 支持无障碍访问

## 📋 验收标准

- [ ] 文字在深色背景下清晰可读
- [ ] 不同功能区域有明确的视觉区分
- [ ] 交互元素状态清晰可辨
- [ ] 整体视觉层次合理有序
- [ ] 空白区域得到合理利用
- [ ] 通过无障碍测试工具验证

### 前端优化重点
1. **CSS变量系统**：建立完整的深色模式颜色变量
2. **组件库适配**：确保 shadcn/ui 组件完全支持深色模式
3. **状态管理**：优化主题切换的用户体验
4. **性能优化**：避免主题切换时的闪烁问题

### 设计系统完善
1. **颜色指南**：制定详细的深色模式颜色使用规范
2. **组件文档**：更新设计系统文档中的深色模式示例
3. **测试流程**：建立深色模式的设计验证流程

## 🚀 优先级

**高优先级** - 这个问题直接影响产品的可用性和用户体验，建议尽快解决。

## 📝 相关文档

- [UI 设计规范](内部文档链接)
- [前后端和插件规范](内部文档链接)
- [shadcn/ui 深色模式指南](https://ui.shadcn.com/docs/dark-mode)
