### ISSUE TITLE
推送 tag 后自动发布 Release 的最佳实践方案设计（推荐 ncipollo/release-action）

### ISSUE THREAD

**Issue by kubbot** [telepace/nexus#58]
## 背景

随着项目规模扩大，前后端、扩展等多模块协同开发，自动化发布流程变得尤为重要。我们希望在推送 tag 后，自动生成 Release、自动上传构建产物，并自动生成 changelog，提升交付效率和规范性。

## 方案分析

主流方案有：
- GitHub 官方 actions（如 actions/create-release）：官方维护，稳定但功能基础。
- softprops/action-gh-release：社区流行，支持多 assets 上传，需配合其他 action 生成 changelog。
- ncipollo/release-action：功能丰富，支持 changelog 自动生成、assets 上传、草稿、预发布等，社区活跃，适合 monorepo 场景。
- 自定义脚本：灵活但维护成本高。

## 推荐方案

**强烈推荐使用 [ncipollo/release-action](https://github.com/ncipollo/release-action) 作为核心 release 步骤，配合 tag 推送触发。**

- 支持 changelog 自动生成（可选 conventional-changelog-action 美化日志）
- 支持多 assets 上传，适合前后端/扩展等多产物
- 配置简单，文档完善，社区活跃
- 适合 monorepo 多语言/多模块场景

## 推荐流程

```mermaid
flowchart TD
    A[推送 tag] --> B[GitHub Actions 触发]
    B --> C[构建前端/后端/扩展产物]
    C --> D[自动生成 changelog]
    D --> E[自动创建 Release]
    E --> F[上传构建产物 assets]
    F --> G[发布 Release]
```

## 关键配置示例

```yaml
# .github/workflows/release.yml
name: Release
on:
  push:
    tags:
      - 'v*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Artifacts
        run: |
          # 构建前端/后端/扩展产物
          pnpm build
          # 假设产物输出到 dist/
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/**"
          generateReleaseNotes: true
```

## 任务拆解
- [ ] 新建 release.yml，集成 ncipollo/release-action
- [ ] 支持多产物自动上传
- [ ] 支持 changelog 自动生成
- [ ] 补充文档说明

---
如有更优建议欢迎补充。

@cubxxw
