### ISSUE TITLE
完整实现 GitHub 自动发布 Release 工作流

### ISSUE THREAD

**Issue by kubbot** [telepace/nexus#59]
## 背景补充

在 [#58](https://github.com/telepace/nexus/issues/58) 中，我们已经确定使用 ncipollo/release-action 作为自动发布 Release 的核心解决方案。现在需要编写完整的实现方案，并配置 BOT_GITHUB_TOKEN 作为推送机器人的 token。

## 详细实现

我将创建 `.github/workflows/release.yml` 文件，实现以下功能：
1. 在推送 tag 时触发自动构建和发布
2. 使用 BOT_GITHUB_TOKEN 而非默认 token 进行权限认证
3. 针对 monorepo 结构，分别构建前端、后端、扩展等模块
4. 自动生成 changelog 和 Release 说明
5. 上传构建产物作为 Release assets

### 完整的 workflow 文件

```yaml
name: Auto Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整历史以生成正确的 changelog

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'pnpm'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'uv'

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.4.15"
          enable-cache: true

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: false

      # 缓存 pnpm 依赖
      - name: Cache pnpm dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pnpm-store
            **/node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      # 准备环境文件
      - name: Prepare environment
        run: |
          cp .env.example .env
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      # 构建前端
      - name: Build Frontend
        run: |
          cd frontend
          pnpm install
          pnpm run build
          mkdir -p ../dist
          tar -czf ../dist/frontend-${{ env.VERSION }}.tar.gz .next public

      # 构建后端
      - name: Build Backend
        run: |
          cd backend
          uv pip install -e .
          uv pip install build wheel
          python -m build
          mkdir -p ../dist
          cp dist/*.whl ../dist/

      # 构建扩展
      - name: Build Extension
        run: |
          cd extension
          pnpm install
          pnpm run build:with-tailwind
          pnpm run package
          mkdir -p ../dist
          cp build/chrome-mv3-prod.zip ../dist/extension-${{ env.VERSION }}.zip

      # 构建管理面板
      - name: Build Admin
        run: |
          cd admin
          pnpm install
          pnpm exec vite build
          mkdir -p ../dist
          tar -czf ../dist/admin-${{ env.VERSION }}.tar.gz dist

      # 构建网站
      - name: Build Website
        run: |
          cd website
          pnpm install
          pnpm run build
          mkdir -p ../dist
          tar -czf ../dist/website-${{ env.VERSION }}.tar.gz .next public

      # 获取上次发布以来的变更
      - name: Generate changelog
        id: changelog
        uses: conventional-changelog/conventional-changelog-action@v1
        with:
          config-file: '.releaserc.json'
          output-file: 'CHANGELOG.md'
          skip-on-empty: false

      # 使用 ncipollo/release-action 创建 Release
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*"
          generateReleaseNotes: true
          bodyFile: "CHANGELOG.md"
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          draft: false
          prerelease: ${{ contains(github.ref, '-rc') || contains(github.ref, '-beta') || contains(github.ref, '-alpha') }}
```

### 配置文件

需要创建 `.releaserc.json` 文件用于生成 changelog:

```json
{
  "branches": ["main"],
  "plugins": [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    "@semantic-release/changelog",
    "@semantic-release/github"
  ]
}
```

## 环境准备

1. 需要在 GitHub 项目设置中添加 Secret：`BOT_GITHUB_TOKEN`，用于机器人访问仓库和创建 Release
2. 该 token 需要具有 repo 权限以创建 Release 和上传 assets

## 实施步骤

1. 创建上述 `.github/workflows/release.yml` 文件
2. 创建 `.releaserc.json` 配置文件
3. 在 GitHub 项目 Settings → Secrets and variables → Actions 中添加 `BOT_GITHUB_TOKEN`
4. 推送一个版本 tag 进行测试，如 `git tag v0.1.0 && git push origin v0.1.0`

## 注意事项

1. BOT_GITHUB_TOKEN 不同于默认的 GITHUB_TOKEN，具有更多权限，可以触发其他工作流
2. 如需支持自动通知到其他系统，可额外添加 webhook 配置
3. 建议遵循语义化版本规范（Semantic Versioning）命名 tag

@cubxxw
